### ISSUE TITLE
App crash When back to main screen after Change System Time and Synch

### ISSUE THREAD

**Issue by 159159951** [google/google-authenticator-android#75]
Here is logcat:

 FATAL EXCEPTION: main
                                                                                           Process: com.google.android.apps.authenticator2.os, PID: 24056
                                                                                           java.lang.RuntimeException: Unable to start activity ComponentInfo{com.google.android.apps.authenticator2.os/com.google.android.apps.authenticator.timesync.SettingsTimeCorrectionActivity}: java.lang.ClassCastException: java.lang.Integer cannot be cast to java.lang.String
                                                                                               at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2646)
                                                                                               at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2707)
                                                                                               at android.app.ActivityThread.-wrap12(ActivityThread.java)
                                                                                               at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1460)
                                                                                               at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                                               at android.os.Looper.loop(Looper.java:154)
                                                                                               at android.app.ActivityThread.main(ActivityThread.java:6077)
                                                                                               at java.lang.reflect.Method.invoke(Native Method)
                                                                                               at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:866)
                                                                                               at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:756)
                                                                                            Caused by: java.lang.ClassCastException: java.lang.Integer cannot be cast to java.lang.String
                                                                                               at android.app.SharedPreferencesImpl.getString(SharedPreferencesImpl.java:225)
                                                                                               at android.preference.Preference.getPersistedString(Preference.java:1472)
                                                                                               at android.preference.EditTextPreference.onSetInitialValue(EditTextPreference.java:160)
                                                                                               at android.preference.Preference.dispatchSetInitialValue(Preference.java:1388)
                                                                                               at android.preference.Preference.onAttachedToHierarchy(Preference.java:1182)
                                                                                               at android.preference.PreferenceGroup.addPreference(PreferenceGroup.java:163)
                                                                                               at android.preference.PreferenceGroup.addItemFromInflater(PreferenceGroup.java:105)
                                                                                               at android.preference.PreferenceGroup.addItemFromInflater(PreferenceGroup.java:104)
                                                                                               at android.preference.GenericInflater.rInflate(GenericInflater.java:490)
                                                                                               at android.preference.GenericInflater.inflate(GenericInflater.java:327)
                                                                                               at android.preference.GenericInflater.inflate(GenericInflater.java:264)
                                                                                               at android.preference.PreferenceManager.inflateFromResource(PreferenceManager.java:280)
                                                                                               at android.preference.PreferenceActivity.addPreferencesFromResource(PreferenceActivity.java:1521)
                                                                                               at com.google.android.apps.authenticator.timesync.SettingsTimeCorrectionActivity.onCreate(SettingsTimeCorrectionActivity.java:35)
                                                                                               at android.app.Activity.performCreate(Activity.java:6662)
                                                                                               at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1118)
                                                                                               at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2599)
                                                                                               at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2707) 
                                                                                               at android.app.ActivityThread.-wrap12(ActivityThread.java) 
                                                                                               at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1460) 
                                                                                               at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                                               at android.os.Looper.loop(Looper.java:154) 
                                                                                               at android.app.ActivityThread.main(ActivityThread.java:6077) 
                                                                                               at java.lang.reflect.Method.invoke(Native Method) 
                                                                                               at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:866) 
                                                                                               at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:756)

**Comment by LIFEIMPACT** [comment]
How can I Adjust Authenticator internal clock ?, Because it appears already be in sync with Google servers.

**Comment by LIFEIMPACT** [comment]
How can you help me to rectify it pls, my data is crucial.

**Comment by ThomasHabets** [comment]
@LIFEIMPACT you have not described your problem **at all**.

But also, let me guess: Bitcoin?

**Comment by ThomasHabets** [comment]
No response
